import fs from 'node:fs/promises';

const path = 'work/build_dashboard_clean.mjs';
let s = await fs.readFile(path, 'utf8');

const cssNeedle = '.bar-value{position:absolute;top:-20px;left:50%;transform:translateX(-50%);font-size:10px;font-weight:700;white-space:nowrap}';
const cssInsert = cssNeedle + '.bar-value small{display:block;font-size:9px;font-weight:800;margin-top:3px}.delta-up{color:var(--green)}.delta-down{color:var(--red)}.trend-summary{font-size:10px;color:var(--muted);margin-top:4px}.trend-summary b{font-size:12px}.trend-summary .up{color:var(--green)}.trend-summary .down{color:var(--red)}';
if (!s.includes('.bar-value small{')) s = s.replace(cssNeedle, cssInsert);

const npsPanelNeedle = '<div class="panel-question">¿La recomendación mejora o empeora?</div></div></div><div class="bar-chart" id="npsChart"></div>';
const npsPanelInsert = '<div class="panel-question">¿La recomendación mejora o empeora?</div><div id="npsVariation" class="trend-summary"></div></div></div><div class="panel-head"><div><h2>Muestras por mes</h2><div class="panel-question">¿Cuántas respuestas tenemos y cómo varían contra el mes anterior?</div></div></div><div class="bar-chart" id="sampleChart"></div><div class="panel-head"><div><h2>Evolución mensual del NPS</h2></div></div><div class="bar-chart" id="npsChart"></div>';
s = s.replace(npsPanelNeedle, npsPanelInsert);

const categoryNeedle = '<div class="panel-question">¿Qué proporción del feedback representa cada dolor por mes?</div></div><div class="filter">';
const categoryInsert = '<div class="panel-question">¿Qué proporción del feedback representa cada dolor por mes?</div><div id="categoryVariation" class="trend-summary"></div></div><div class="filter">';
s = s.replace(categoryNeedle, categoryInsert);

const renderOld = "function renderBarChart(container,months,getValue,formatValue,colorFn){container.innerHTML='';if(!months.length){container.innerHTML='<div class=\"empty\">No hay datos para esta selección.</div>';return}var values=months.map(getValue),max=Math.max.apply(null,values.map(function(v){return Math.abs(v||0)}).concat([1]));months.forEach(function(m,i){var v=values[i],item=document.createElement('div');item.className='bar-item';var track=document.createElement('div');track.className='bar-track';var bar=document.createElement('div');bar.className='bar '+colorFn(v);bar.style.height=Math.max(Math.abs(v)/max*175,3)+'px';var value=document.createElement('span');value.className='bar-value';value.textContent=formatValue(v);bar.appendChild(value);track.appendChild(bar);var label=document.createElement('div');label.className='month-label';label.textContent=monthLabel(m);item.appendChild(track);item.appendChild(label);container.appendChild(item)})}";
const renderNew = "function renderBarChart(container,months,getValue,formatValue,colorFn,deltaFn,deltaFormatFn){container.innerHTML='';if(!months.length){container.innerHTML='<div class=\"empty\">No hay datos para esta selección.</div>';return}var values=months.map(getValue),max=Math.max.apply(null,values.map(function(v){return Math.abs(v||0)}).concat([1]));months.forEach(function(m,i){var v=values[i],item=document.createElement('div');item.className='bar-item';var track=document.createElement('div');track.className='bar-track';var bar=document.createElement('div');bar.className='bar '+colorFn(v);bar.style.height=Math.max(Math.abs(v)/max*175,3)+'px';var value=document.createElement('span');value.className='bar-value';var delta=deltaFn?deltaFn(m,i,months,values):null;value.innerHTML=formatValue(v)+(delta===null||delta===undefined?'':'<small class=\"'+(delta>=0?'delta-up':'delta-down')+'\">Δ '+deltaFormatFn(delta)+'</small>');bar.appendChild(value);track.appendChild(bar);var label=document.createElement('div');label.className='month-label';label.textContent=monthLabel(m);item.appendChild(track);item.appendChild(label);container.appendChild(item)})}";
s = s.replace(renderOld, renderNew);

const callOld = "var trend={};months.forEach(function(m){trend[m]=responses.filter(function(x){return x.month===m})});renderBarChart($('npsChart'),months,function(m){return calcNps(trend[m])||0},function(v){return v.toFixed(1)},function(){return 'nps-white'});";
const callNew = "var trend={};months.forEach(function(m){trend[m]=responses.filter(function(x){return x.month===m})});renderBarChart($('sampleChart'),months,function(m){return trend[m].length},function(v){return fmt(v)},function(){return 'nps-white'},function(m,i,ms,values){if(i===0)return null;var prev=values[i-1];return prev?((values[i]-prev)/prev*100):null},function(v){return (v>=0?'+':'')+v.toFixed(1)+'%'});renderBarChart($('npsChart'),months,function(m){return calcNps(trend[m])||0},function(v){return v.toFixed(1)},function(){return 'nps-white'},function(m,i,ms,values){if(i===0)return null;return values[i]-values[i-1]},function(v){return (v>=0?'+':'')+v.toFixed(1)+' pts'});var npsDelta=months.length>1?calcNps(trend[months[months.length-1]])-calcNps(trend[months[months.length-2]]):null;$('npsVariation').innerHTML=npsDelta===null?'Variación: sin mes anterior':'Variación vs '+monthLabel(months[months.length-2])+' · <b class=\"'+(npsDelta>=0?'up':'down')+'\">'+(npsDelta>=0?'+':'')+npsDelta.toFixed(1)+' pts</b>';";
s = s.replace(callOld, callNew);

const variationMarker = 'var p=pct(pro),n=pct(neu);';
const categoryVariation = "var categoryDeltaText='Selecciona una categoría para ver su variación mensual.';if(selectedTrend!=='all'&&trendMonths.length>1){var currentMonth=trendMonths[trendMonths.length-1],previousMonth=trendMonths[trendMonths.length-2],currentRows=feedback.filter(function(x){return x.month===currentMonth&&activeCategory(x)===selectedTrend}),previousRows=feedback.filter(function(x){return x.month===previousMonth&&activeCategory(x)===selectedTrend}),currentTotal=feedback.filter(function(x){return x.month===currentMonth}).length||1,previousTotal=feedback.filter(function(x){return x.month===previousMonth}).length||1,currentPct=currentRows.length/currentTotal*100,previousPct=previousRows.length/previousTotal*100,categoryDelta=currentPct-previousPct;categoryDeltaText='Variación '+monthLabel(currentMonth)+' vs '+monthLabel(previousMonth)+' · <b class=\"'+(categoryDelta>=0?'up':'down')+'\">'+(categoryDelta>=0?'+':'')+categoryDelta.toFixed(1)+' pp</b>'}else if(selectedTrend==='all'){categoryDeltaText='Selecciona una categoría para ver su variación vs mes anterior.'}$('categoryVariation').innerHTML=categoryDeltaText;";
s = s.replace(variationMarker, categoryVariation + variationMarker);

await fs.writeFile(path, s, 'utf8');
console.log('monthly samples and variations added');
