import fs from 'node:fs/promises';
const p='outputs/medallia_cx_nps_2026-08-14/medallia_cx_nps_dashboard.html'; let h=await fs.readFile(p,'utf8');
h=h.replace('</style>','.chart-stack{display:grid;grid-template-columns:1fr;gap:14px;margin-bottom:14px}.coverage-track{height:18px;display:flex;background:#302c29;border-radius:9px;overflow:hidden;margin:18px 0 14px}.coverage-ok{background:var(--green);height:100%;transition:width .25s}.coverage-pending{background:var(--red);height:100%;transition:width .25s}.coverage-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.coverage-stat{padding:12px;background:var(--surface2);border-radius:8px}.coverage-stat b{display:block;font-size:23px;margin-top:5px}@media(max-width:760px){.coverage-grid{grid-template-columns:1fr}}</style>');
h=h.replace('<section class="two"><article class="panel"><div class="panel-head"><div><h2>Evolución mensual del NPS','<section class="chart-stack"><article class="panel"><div class="panel-head"><div><h2>Evolución mensual del NPS');
const coverage='<article class="panel"><div class="panel-head"><div><h2>Cobertura de categorización</h2><div class="panel-question">¿Cuántos feedbacks tienen categoría y cuántos siguen pendientes?</div></div></div><div class="coverage-track"><div class="coverage-ok" id="coverageOk"></div><div class="coverage-pending" id="coveragePending"></div></div><div class="coverage-grid"><div class="coverage-stat"><span class="klabel">Categorizados</span><b class="positive" id="coverageClassified"></b><span class="ksub" id="coverageClassifiedPct"></span></div><div class="coverage-stat"><span class="klabel">No categorizados / pendientes</span><b class="negative" id="coverageUnclassified"></b><span class="ksub" id="coverageUnclassifiedPct"></span></div></div><div class="footer-note" id="coverageNote"></div></article>';
h=h.replace('<article class="panel"><div class="panel-head"><div><h2>Comentarios representativos</h2>',coverage+'<article class="panel"><div class="panel-head"><div><h2>Comentarios representativos</h2>');
const coverageJs="var coverageBase=FEEDBACK.filter(function(x){return (activeSegment==='Total'||x.segment===activeSegment)&&(monthFilter.value==='all'||x.month===monthFilter.value)&&(classFilter.value==='all'||x.klass===classFilter.value)});var classifiedCount=coverageBase.filter(function(x){return Boolean(activeCategory(x))}).length;var unclassifiedCount=coverageBase.length-classifiedCount;var classifiedPct=coverageBase.length?classifiedCount/coverageBase.length*100:0;var unclassifiedPct=100-classifiedPct;$('coverageOk').style.width=classifiedPct+'%';$('coveragePending').style.width=unclassifiedPct+'%';$('coverageClassified').textContent=fmt(classifiedCount);$('coverageUnclassified').textContent=fmt(unclassifiedCount);$('coverageClassifiedPct').textContent=classifiedPct.toFixed(1)+'% de la base';$('coverageUnclassifiedPct').textContent=unclassifiedPct.toFixed(1)+'% de la base';$('coverageNote').textContent=classifierFilter.value==='ollama'?'Ollama muestra únicamente registros procesados y validados; los demás permanecen pendientes.':'El modelo local cubre la base completa con comentario.';";
h=h.replace('var commentPool=',coverageJs+'var commentPool=');
await fs.writeFile(p,h,'utf8'); console.log('coverage chart and stacked evolutions added');
